### ISSUE TITLE
Hello World

### ISSUE THREAD

**Issue by eoinfogarty** [nbhd/welcome-to-android#1]
push a basic project with one activity and one textview

**Comment by eoinfogarty** [comment]
when ready, make PR and tag me(Eoin) and johnny (Shono san)

**Comment by bowyer-app** [comment]
like this
- [ ] @eoinfogarty 
- [ ] @bowyer-app

**Comment by eoinfogarty** [comment]
we need permission to check and merge, sorry 🙇
